[package]
name = "rust_poker_env"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_poker_env"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
rand = "0.8"
rs_poker = "4.0.0"

[package.metadata.maturin]
name = "rust_poker_env"